server:
  port: 8084

spring:
  application:
    name: rental-notify
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848

knife4j:
  enable: true
  openapi:
    title: 通知服务API
    version: 1.0.0
